version: '3.8'

services:
  mage:
    image: mageai/mageai:0.8.69
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - /mnt/pve/data/vmdir/mage_data:/home/src
    environment:
      - USER_CODE_PATH=/home/src
    restart: unless-stopped