version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - /mnt/pve/data/vmdir/mage-data:/home/src
    environment:
      - USER_CODE_PATH=/home/src
    restart: unless-stopped